### ISSUE TITLE
When I try to run config.py file, I get the following error 'NoModuleFoundError'

### ISSUE THREAD

**Issue by mkdthanga** [Repsay/tia-openness-api-client#2]
```
Traceback (most recent call last):
  File "d:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main\tia_portal\config.py", line 12, in <module>
    from tia_portal.version import TiaVersion
ModuleNotFoundError: No module named 'tia_portal'
```
What should I do in order to run the config.py script?

Thank you in advance

Regards,
Thangz

**Comment by Repsay** [comment]
You probably did not install the code to your environment, but I see that there also is no setup file for this. What you could do is create a setup.py file in the main folder.  "d:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main\". Then you could run the 

```
pip install -e . 
```

Command to add the library to your environment.

**Comment by mkdthanga** [comment]
Now I get this below Import error:
```
(.python_venv) PS D:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main> & d:/Thangz/Projekte/dev/.python_venv/Scripts/python.exe "d:/Thangz/Projekte/dev/TIA openness/tia-openness-api-client-main/tia_portal/config.py"
Traceback (most recent call last):
  File "d:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main\tia_portal\config.py", line 12, in <module>
    from tia_portal.version import TiaVersion
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\__init__.py", line 14, in <module>
    from tia_portal.protocol.composition import Composition, CompositionItem
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\protocol\composition.py", line 3, in <module>
    from typing import Any, Optional, Protocol, Self, TypeVar, Iterator
ImportError: cannot import name 'Self' from 'typing' (C:\Users\Mukara\AppData\Local\Programs\Python\Python310\lib\typing.py)
```

Please help!

**Comment by Repsay** [comment]
You could solve your issue by either updating to python 3.11 or using the package typing-extensions. https://pypi.org/project/typing-extensions/#data

**Comment by mkdthanga** [comment]
That package is already installed there, but not working:

```
(.python_venv) PS D:\Thangz\Projekte\dev> pip install typing-extensions
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)
Requirement already satisfied: typing-extensions in d:\thangz\projekte\dev\.python_venv\lib\site-packages (4.3.0)
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\thangz\projekte\dev\.python_venv\lib\site-packages)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(.python_venv) PS D:\Thangz\Projekte\dev> & d:/Thangz/Projekte/dev/.python_venv/Scripts/python.exe "d:/Thangz/Projekte/dev/TIA openness/tia-openness-api-client-main/tia_portal/config.py"
Traceback (most recent call last):
  File "d:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main\tia_portal\config.py", line 12, in <module>
    from tia_portal.version import TiaVersion
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\__init__.py", line 14, in <module>
    from tia_portal.protocol.composition import Composition, CompositionItem
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\protocol\composition.py", line 3, in <module>
    from typing import Any, Optional, Protocol, Self, TypeVar, Iterator
ImportError: cannot import name 'Self' from 'typing' (C:\Users\Mukara\AppData\Local\Programs\Python\Python310\lib\typing.py)
(.python_venv) PS D:\Thangz\Projekte\dev> 
```

**Comment by Repsay** [comment]
When using the typing_extensions package you should also change the source code of the file `tia_portal\protocol\composition.py` by removing Self from `from typing import Self` and add a new line `from typing_extensions import Self`

**Comment by mkdthanga** [comment]
Now I ran your example code and got this file not found error although the file is present at mentioned directory:
```
(.python_venv) PS D:\Thangz\Projekte\dev> & d:/Thangz/Projekte/dev/.python_venv/Scripts/python.exe "d:/Thangz/Projekte/dev/TIA openness/tia-openness-api-client-main/tia_portal/test_client.py"
Traceback (most recent call last):
  File "d:\Thangz\Projekte\dev\TIA openness\tia-openness-api-client-main\tia_portal\test_client.py", line 8, in <module>
    tia_client.open_project("D:\\Thangz\\Projekte\dev\\TIA openness\\PythonTest", "PythonTest")
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\__init__.py", line 2039, in open_project
    self.project.open()
  File "d:\thangz\projekte\dev\tia openness\tia-openness-api-client-main\tia_portal\__init__.py", line 2178, in open
    raise tia_e.TIAProjectNotFound(f"File {file_path} does not exist")
tia_portal.exceptions.TIAProjectNotFound: File D:\Thangz\Projekte\dev\TIA openness\PythonTest\PythonTest\PythonTest.ap17 does not exist
```
Moreover I want ask if you tried any code to perform hardware generation like making subnet connection and topology connections of the added devices using your client tool?

**Comment by Repsay** [comment]
Make sure you have a ap17 file located in path `D:\Thangz\Projekte\dev\TIA openness\PythonTest\PythonTest` notice the double PythonTest at the end. Might be the case that you should edit the `D:\\Thangz\\Projekte\dev\\TIA openness\\PythonTest` to `D:\\Thangz\\Projekte\dev\\TIA openness`.

Also regarding your question. No I did not use or develop the tool to work with the hardware generation or connections. I made this tool for my graduation project and in that project I only focussed on generating software blocks and user groups.

That's why in my other repository [https://github.com/Repsay/tia-portal-xml-generator](tia-openess-xml-generator) I created software to generate new XML files from scratch.
